apiVersion: skaffold/v2alpha3
kind: Config
deploy:
  kubectl:
    manifests:
      - ./infra/k8s/*
build:
  local:
    push: false
  artifacts:
    - image: alexander-gc/auth
      context: auth
      docker:
        dockerfile: Dockerfile
        target: auth
      sync:
        manual:
          - src: "server/**/*.ts"
            dest: .
    - image: alexander-gc/tickets
      context: tickets
      docker:
        dockerfile: Dockerfile
        target: tickets
      sync:
        manual:
          - src: "server/**/*.ts"
            dest: .
    - image: alexander-gc/client
      context: client
      docker:
        dockerfile: Dockerfile
        target: client
      sync:
        manual:
          - src: "**/*.js"
            dest: .
