name: tests-auth

on:
  pull_request:
    branches: [main, develop]
    types: [opened, synchronize, reopened]
    paths:
      - "auth/**"
  push:
    branches: [main, develop]
    paths:
      - "auth/**"

jobs:
  avoid_reduncy:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd auth && npm ci
      - name: Run Test
        run: cd auth && npm run test:ci

  deploy_aws:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/main' }}
    #needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        run: echo "Starting deployment to AWS"

  deploy_heroku:
    if: ${{ github.event_name == 'push' && github.ref == 'refs/heads/develop' }}
    #needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Heroku
        run: echo "Starting deployment to Heroku"
