name: tests-auth

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]
    paths:
      - "auth/**"
  push:
    branches: [main]
    paths:
      - "auth/**"

jobs:
  avoid_reduncy:
    runs-on: ubuntu-18.04
    steps:
      - name: Cancel Previous Redundant Builds
        uses: styfle/cancel-workflow-action@0.9.1
        with:
          access_token: ${{ github.token }}

  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: cd auth && npm ci
      - name: Run Test
        run: cd auth && npm run test:ci

  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to AWS
        if: ${{ github.event_name == 'push' }}
        run: echo "Starting deployment to AWS"
